### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by xandark** [tingtron/terra#1]
Could you provide a disk image? Or at the very least give us detailed instructions on how to build this so we can see for ourselves? I missed KFest but read about this in Juiced.GS and want to see this in action.

**Comment by tingtron** [comment]
Thank you for your interest in the KFest / HackFest 2023 entries.

Please follow the directions to setup Kyan Pascal environment and run the example program in the README:
- https://github.com/tingtron/terra/tree/main/LORES

which is compiled following the usual conventions with dependency on proprietary software, and familiarity with a related development environment.

Let me know if you have specific issues or questions.👌

**Comment by xandark** [comment]
I read the link you mentioned and it says:

"Make sure to read the manuals and be able to compile and run various Pascal examples"

No. I just want to run the program, not learn another dev environment.

**Comment by xandark** [comment]
Awful.

**Comment by tingtron** [comment]
Your trolling and harassment has been reported to GitHub.
